Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_version = ">= 0"
  
  config.vm.define "k3s-server" do |server|
    server.vm.hostname = "k3s-server"
    server.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus   = 2
    end

    server.vm.network "public_network", ip: "192.168.1.100"
    server.vm.provision "shell",
        env: {
                "K3S_TOKEN" => ENV.fetch("K3S_TOKEN", "super-secret-k3s-token")
            },
        inline: <<-SHELL
            curl -sfL https://get.k3s.io | sh -s - server
        SHELL
    end

  config.vm.define "k3s-agent-1" do |worker|
    worker.vm.hostname = "k3s-agent-1"
    worker.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus   = 2
    end

    worker.vm.network "public_network", ip: "192.168.1.101"
    worker.vm.provision "shell",
        env: {
                "K3S_TOKEN" => ENV.fetch("K3S_TOKEN", "super-secret-k3s-token"),
                "K3S_URL" => "https://192.168.1.100:6443"
            },
        inline: <<-SHELL
            curl -sfL https://get.k3s.io | sh -
        SHELL
  end

  config.vm.define "k3s-agent-2" do |worker|
    worker.vm.hostname = "k3s-agent-2"
    worker.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus   = 2
    end

    worker.vm.network "public_network", ip: "192.168.1.102"
    worker.vm.provision "shell",
        env: {
                "K3S_TOKEN" => ENV.fetch("K3S_TOKEN", "super-secret-k3s-token"),
                "K3S_URL" => "https://192.168.1.100:6443"
            },
        inline: <<-SHELL
            curl -sfL https://get.k3s.io | sh -
        SHELL
  end
end
